name: Build and Test

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
    branches:
      - development

jobs:
  validate-labels:
    name: Labels Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Required Labels
        uses: actions/github-script@v7
        id: labels
        with:
          script: |
            const labelsSet = ['minor', 'patch', 'major'];
            const labels = context.payload.pull_request.labels.map((label) => label.name);
            
            if (!labelsSet.some(label => labels.includes(label))) {
              core.setFailed(`❌ Please add one of the following labels to proceed: "major", "minor", "patch".`);
              return;
            }