name: Deploy to Docker Hub

on:
  workflow_dispatch:
    inputs:
      code:
        description: "Secure Code"
        type: string
        required: true

jobs:
  docker:
    if: ${{ inputs.code == secrets.SECURE_CODE }}
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Latest Changes
        run: git pull origin main

      - name: Get Latest Version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"

      - name: Install Dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Run Build (Frontend)
        working-directory: ./frontend
        run: npm run build

      - name: Install Dependencies (BackEnd)
        working-directory: ./backend
        run: npm install

      - name: Run Tests (BackEnd)
        working-directory: ./backend
        run: npm test

      - name: print
        run: echo "VERSION ${{ env.VERSION }}"

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_HUB_USER }}
#          password: ${{ secrets.DOCKER_HUB_TOKEN }}
#
#      - name: Build and Push to Docker Hub
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          build-args: |
#            APP_VERSION=${{ env.VERSION }}
#          push: true
#          tags: |
#            ${{ secrets.DOCKER_HUB_USER }}/mockly:${{ env.VERSION }}
#            ${{ secrets.DOCKER_HUB_USER }}/mockly:latest